name: Build

on:
  push:
    branches:
     - master
  pull_request:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          
      - name: build
        run: make -j2

      - name: test
        run: ls -la
        
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          prerelease: false
          draft: false
          body: ${{ github.event.head_commit.message }}
          files: fuck-u.nro
          name: "Switch Release #${{ github.run_number }}"
